# Generated by Django 6.1.1 on 2026-10-02 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_customer_user_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='debt',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debts', to='main.customer'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Не оплачен'), ('partial', 'Частично оплачен'), ('paid', 'Оплачен'), ('cancelled', 'Отменён')], default='unpaid', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Владелец'), ('cashier', 'Кассир'), ('client', 'Клиент')], default='owner', max_length=10),
        ),
    ]
