# Generated by Django 6.1.1 on 2026-10-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_customer_is_archived_alter_debt_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlog',
            name='details',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
