# Generated by Django 6.1.1 on 2026-10-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_actionlog_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partially paid'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='unpaid', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('cashier', 'Cashier'), ('client', 'Customer')], default='owner', max_length=10),
        ),
    ]
